package com.microclouds.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table area
 *
 * @mbg.generated do_not_delete_during_merge Sat Dec 22 15:48:24 CST 2018
 */
public class Area implements Serializable {
    /**
     * Database Column Remarks:
     *   自增id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.id
     *
     * @mbg.generated Sat Dec 22 15:48:24 CST 2018
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   区域的编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.area_code
     *
     * @mbg.generated Sat Dec 22 15:48:24 CST 2018
     */
    private String areaCode;

    /**
     * Database Column Remarks:
     *   区域的名字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.area_name
     *
     * @mbg.generated Sat Dec 22 15:48:24 CST 2018
     */
    private String areaName;

    /**
     * Database Column Remarks:
     *   区域对应的的城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.city_code
     *
     * @mbg.generated Sat Dec 22 15:48:24 CST 2018
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table area
     *
     * @mbg.generated Sat Dec 22 15:48:24 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.id
     *
     * @return the value of area.id
     *
     * @mbg.generated Sat Dec 22 15:48:24 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.id
     *
     * @param id the value for area.id
     *
     * @mbg.generated Sat Dec 22 15:48:24 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.area_code
     *
     * @return the value of area.area_code
     *
     * @mbg.generated Sat Dec 22 15:48:24 CST 2018
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.area_code
     *
     * @param areaCode the value for area.area_code
     *
     * @mbg.generated Sat Dec 22 15:48:24 CST 2018
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.area_name
     *
     * @return the value of area.area_name
     *
     * @mbg.generated Sat Dec 22 15:48:24 CST 2018
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.area_name
     *
     * @param areaName the value for area.area_name
     *
     * @mbg.generated Sat Dec 22 15:48:24 CST 2018
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.city_code
     *
     * @return the value of area.city_code
     *
     * @mbg.generated Sat Dec 22 15:48:24 CST 2018
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.city_code
     *
     * @param cityCode the value for area.city_code
     *
     * @mbg.generated Sat Dec 22 15:48:24 CST 2018
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }
}