package com.microclouds.pojo;

import java.util.ArrayList;
import java.util.List;

public class CloudCapacityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public CloudCapacityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andOccupiedIsNull() {
            addCriterion("occupied is null");
            return (Criteria) this;
        }

        public Criteria andOccupiedIsNotNull() {
            addCriterion("occupied is not null");
            return (Criteria) this;
        }

        public Criteria andOccupiedEqualTo(Long value) {
            addCriterion("occupied =", value, "occupied");
            return (Criteria) this;
        }

        public Criteria andOccupiedNotEqualTo(Long value) {
            addCriterion("occupied <>", value, "occupied");
            return (Criteria) this;
        }

        public Criteria andOccupiedGreaterThan(Long value) {
            addCriterion("occupied >", value, "occupied");
            return (Criteria) this;
        }

        public Criteria andOccupiedGreaterThanOrEqualTo(Long value) {
            addCriterion("occupied >=", value, "occupied");
            return (Criteria) this;
        }

        public Criteria andOccupiedLessThan(Long value) {
            addCriterion("occupied <", value, "occupied");
            return (Criteria) this;
        }

        public Criteria andOccupiedLessThanOrEqualTo(Long value) {
            addCriterion("occupied <=", value, "occupied");
            return (Criteria) this;
        }

        public Criteria andOccupiedIn(List<Long> values) {
            addCriterion("occupied in", values, "occupied");
            return (Criteria) this;
        }

        public Criteria andOccupiedNotIn(List<Long> values) {
            addCriterion("occupied not in", values, "occupied");
            return (Criteria) this;
        }

        public Criteria andOccupiedBetween(Long value1, Long value2) {
            addCriterion("occupied between", value1, value2, "occupied");
            return (Criteria) this;
        }

        public Criteria andOccupiedNotBetween(Long value1, Long value2) {
            addCriterion("occupied not between", value1, value2, "occupied");
            return (Criteria) this;
        }

        public Criteria andAllCapacityIsNull() {
            addCriterion("all_capacity is null");
            return (Criteria) this;
        }

        public Criteria andAllCapacityIsNotNull() {
            addCriterion("all_capacity is not null");
            return (Criteria) this;
        }

        public Criteria andAllCapacityEqualTo(Long value) {
            addCriterion("all_capacity =", value, "allCapacity");
            return (Criteria) this;
        }

        public Criteria andAllCapacityNotEqualTo(Long value) {
            addCriterion("all_capacity <>", value, "allCapacity");
            return (Criteria) this;
        }

        public Criteria andAllCapacityGreaterThan(Long value) {
            addCriterion("all_capacity >", value, "allCapacity");
            return (Criteria) this;
        }

        public Criteria andAllCapacityGreaterThanOrEqualTo(Long value) {
            addCriterion("all_capacity >=", value, "allCapacity");
            return (Criteria) this;
        }

        public Criteria andAllCapacityLessThan(Long value) {
            addCriterion("all_capacity <", value, "allCapacity");
            return (Criteria) this;
        }

        public Criteria andAllCapacityLessThanOrEqualTo(Long value) {
            addCriterion("all_capacity <=", value, "allCapacity");
            return (Criteria) this;
        }

        public Criteria andAllCapacityIn(List<Long> values) {
            addCriterion("all_capacity in", values, "allCapacity");
            return (Criteria) this;
        }

        public Criteria andAllCapacityNotIn(List<Long> values) {
            addCriterion("all_capacity not in", values, "allCapacity");
            return (Criteria) this;
        }

        public Criteria andAllCapacityBetween(Long value1, Long value2) {
            addCriterion("all_capacity between", value1, value2, "allCapacity");
            return (Criteria) this;
        }

        public Criteria andAllCapacityNotBetween(Long value1, Long value2) {
            addCriterion("all_capacity not between", value1, value2, "allCapacity");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cloud_capacity
     *
     * @mbg.generated do_not_delete_during_merge Sat Jan 12 14:49:18 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}