package com.microclouds.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cloud_capacity
 *
 * @mbg.generated do_not_delete_during_merge Sat Jan 12 14:49:18 CST 2019
 */
public class CloudCapacity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_capacity.id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_capacity.user_id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_capacity.occupied
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private Long occupied;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_capacity.all_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private Long allCapacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_capacity.id
     *
     * @return the value of cloud_capacity.id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_capacity.id
     *
     * @param id the value for cloud_capacity.id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_capacity.user_id
     *
     * @return the value of cloud_capacity.user_id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_capacity.user_id
     *
     * @param userId the value for cloud_capacity.user_id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_capacity.occupied
     *
     * @return the value of cloud_capacity.occupied
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public Long getOccupied() {
        return occupied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_capacity.occupied
     *
     * @param occupied the value for cloud_capacity.occupied
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void setOccupied(Long occupied) {
        this.occupied = occupied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_capacity.all_capacity
     *
     * @return the value of cloud_capacity.all_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public Long getAllCapacity() {
        return allCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_capacity.all_capacity
     *
     * @param allCapacity the value for cloud_capacity.all_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void setAllCapacity(Long allCapacity) {
        this.allCapacity = allCapacity;
    }
}