package com.microclouds.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table email
 *
 * @mbg.generated do_not_delete_during_merge Sat Jan 12 14:49:18 CST 2019
 */
public class Email implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.from_real_name
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private String fromRealName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.from_user_id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private Integer fromUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.to_user_id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private Integer toUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.email_title
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private String emailTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.email_content
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private String emailContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.send_date
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private Date sendDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.del_flag
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private Boolean delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table email
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.id
     *
     * @return the value of email.id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.id
     *
     * @param id the value for email.id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.from_real_name
     *
     * @return the value of email.from_real_name
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public String getFromRealName() {
        return fromRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.from_real_name
     *
     * @param fromRealName the value for email.from_real_name
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void setFromRealName(String fromRealName) {
        this.fromRealName = fromRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.from_user_id
     *
     * @return the value of email.from_user_id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public Integer getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.from_user_id
     *
     * @param fromUserId the value for email.from_user_id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void setFromUserId(Integer fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.to_user_id
     *
     * @return the value of email.to_user_id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public Integer getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.to_user_id
     *
     * @param toUserId the value for email.to_user_id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void setToUserId(Integer toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.email_title
     *
     * @return the value of email.email_title
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public String getEmailTitle() {
        return emailTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.email_title
     *
     * @param emailTitle the value for email.email_title
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void setEmailTitle(String emailTitle) {
        this.emailTitle = emailTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.email_content
     *
     * @return the value of email.email_content
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public String getEmailContent() {
        return emailContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.email_content
     *
     * @param emailContent the value for email.email_content
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void setEmailContent(String emailContent) {
        this.emailContent = emailContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.send_date
     *
     * @return the value of email.send_date
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public Date getSendDate() {
        return sendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.send_date
     *
     * @param sendDate the value for email.send_date
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void setSendDate(Date sendDate) {
        this.sendDate = sendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.del_flag
     *
     * @return the value of email.del_flag
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.del_flag
     *
     * @param delFlag the value for email.del_flag
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }
}