package com.microclouds.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table file_system_log
 *
 * @mbg.generated do_not_delete_during_merge Wed Jan 16 16:06:25 CST 2019
 */
public class FileSystemLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_system_log.id
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_system_log.file_id
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_system_log.user_id
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_system_log.log_date
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    private Date logDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_system_log.log_type
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    private String logType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_system_log.file_name
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_system_log.upload_status
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    private String uploadStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_system_log.file_size
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    private Long fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_system_log.del_flag
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    private Boolean delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file_system_log
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_system_log.id
     *
     * @return the value of file_system_log.id
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_system_log.id
     *
     * @param id the value for file_system_log.id
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_system_log.file_id
     *
     * @return the value of file_system_log.file_id
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_system_log.file_id
     *
     * @param fileId the value for file_system_log.file_id
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_system_log.user_id
     *
     * @return the value of file_system_log.user_id
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_system_log.user_id
     *
     * @param userId the value for file_system_log.user_id
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_system_log.log_date
     *
     * @return the value of file_system_log.log_date
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    public Date getLogDate() {
        return logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_system_log.log_date
     *
     * @param logDate the value for file_system_log.log_date
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    public void setLogDate(Date logDate) {
        this.logDate = logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_system_log.log_type
     *
     * @return the value of file_system_log.log_type
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    public String getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_system_log.log_type
     *
     * @param logType the value for file_system_log.log_type
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    public void setLogType(String logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_system_log.file_name
     *
     * @return the value of file_system_log.file_name
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_system_log.file_name
     *
     * @param fileName the value for file_system_log.file_name
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_system_log.upload_status
     *
     * @return the value of file_system_log.upload_status
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    public String getUploadStatus() {
        return uploadStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_system_log.upload_status
     *
     * @param uploadStatus the value for file_system_log.upload_status
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    public void setUploadStatus(String uploadStatus) {
        this.uploadStatus = uploadStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_system_log.file_size
     *
     * @return the value of file_system_log.file_size
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_system_log.file_size
     *
     * @param fileSize the value for file_system_log.file_size
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_system_log.del_flag
     *
     * @return the value of file_system_log.del_flag
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_system_log.del_flag
     *
     * @param delFlag the value for file_system_log.del_flag
     *
     * @mbg.generated Wed Jan 16 16:06:25 CST 2019
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }
}