package com.microclouds.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table message
 *
 * @mbg.generated do_not_delete_during_merge Sat Jan 12 14:49:18 CST 2019
 */
public class Message implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.from_real_name
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private String fromRealName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.from_user_id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private Integer fromUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.to_user_id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private Integer toUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.send_date
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private Date sendDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.type
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.del_flag
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private Boolean delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.from_real_name
     *
     * @return the value of message.from_real_name
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public String getFromRealName() {
        return fromRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.from_real_name
     *
     * @param fromRealName the value for message.from_real_name
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void setFromRealName(String fromRealName) {
        this.fromRealName = fromRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.from_user_id
     *
     * @return the value of message.from_user_id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public Integer getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.from_user_id
     *
     * @param fromUserId the value for message.from_user_id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void setFromUserId(Integer fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.to_user_id
     *
     * @return the value of message.to_user_id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public Integer getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.to_user_id
     *
     * @param toUserId the value for message.to_user_id
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void setToUserId(Integer toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.send_date
     *
     * @return the value of message.send_date
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public Date getSendDate() {
        return sendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.send_date
     *
     * @param sendDate the value for message.send_date
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void setSendDate(Date sendDate) {
        this.sendDate = sendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.type
     *
     * @return the value of message.type
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.type
     *
     * @param type the value for message.type
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.del_flag
     *
     * @return the value of message.del_flag
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.del_flag
     *
     * @param delFlag the value for message.del_flag
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }
}