package com.microclouds.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_log
 *
 * @mbg.generated do_not_delete_during_merge Wed Jan 16 14:59:41 CST 2019
 */
public class UserLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.id
     *
     * @mbg.generated Wed Jan 16 14:59:41 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.user_id
     *
     * @mbg.generated Wed Jan 16 14:59:41 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.log_date
     *
     * @mbg.generated Wed Jan 16 14:59:41 CST 2019
     */
    private Date logDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.user_ip
     *
     * @mbg.generated Wed Jan 16 14:59:41 CST 2019
     */
    private String userIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.log_type
     *
     * @mbg.generated Wed Jan 16 14:59:41 CST 2019
     */
    private String logType;

    /**
     * Database Column Remarks:
     *   日志描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.description
     *
     * @mbg.generated Wed Jan 16 14:59:41 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_log
     *
     * @mbg.generated Wed Jan 16 14:59:41 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.id
     *
     * @return the value of user_log.id
     *
     * @mbg.generated Wed Jan 16 14:59:41 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.id
     *
     * @param id the value for user_log.id
     *
     * @mbg.generated Wed Jan 16 14:59:41 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.user_id
     *
     * @return the value of user_log.user_id
     *
     * @mbg.generated Wed Jan 16 14:59:41 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.user_id
     *
     * @param userId the value for user_log.user_id
     *
     * @mbg.generated Wed Jan 16 14:59:41 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.log_date
     *
     * @return the value of user_log.log_date
     *
     * @mbg.generated Wed Jan 16 14:59:41 CST 2019
     */
    public Date getLogDate() {
        return logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.log_date
     *
     * @param logDate the value for user_log.log_date
     *
     * @mbg.generated Wed Jan 16 14:59:41 CST 2019
     */
    public void setLogDate(Date logDate) {
        this.logDate = logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.user_ip
     *
     * @return the value of user_log.user_ip
     *
     * @mbg.generated Wed Jan 16 14:59:41 CST 2019
     */
    public String getUserIp() {
        return userIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.user_ip
     *
     * @param userIp the value for user_log.user_ip
     *
     * @mbg.generated Wed Jan 16 14:59:41 CST 2019
     */
    public void setUserIp(String userIp) {
        this.userIp = userIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.log_type
     *
     * @return the value of user_log.log_type
     *
     * @mbg.generated Wed Jan 16 14:59:41 CST 2019
     */
    public String getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.log_type
     *
     * @param logType the value for user_log.log_type
     *
     * @mbg.generated Wed Jan 16 14:59:41 CST 2019
     */
    public void setLogType(String logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.description
     *
     * @return the value of user_log.description
     *
     * @mbg.generated Wed Jan 16 14:59:41 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.description
     *
     * @param description the value for user_log.description
     *
     * @mbg.generated Wed Jan 16 14:59:41 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }
}