package com.microclouds.dao;

import com.microclouds.pojo.CloudCapacity;
import com.microclouds.pojo.CloudCapacityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CloudCapacityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    long countByExample(CloudCapacityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int deleteByExample(CloudCapacityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int insert(CloudCapacity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int insertSelective(CloudCapacity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    List<CloudCapacity> selectByExample(CloudCapacityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    CloudCapacity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") CloudCapacity record, @Param("example") CloudCapacityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int updateByExample(@Param("record") CloudCapacity record, @Param("example") CloudCapacityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int updateByPrimaryKeySelective(CloudCapacity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_capacity
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int updateByPrimaryKey(CloudCapacity record);
}