package com.microclouds.dao;

import com.microclouds.pojo.FileSystemLog;
import com.microclouds.pojo.FileSystemLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileSystemLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_log
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    long countByExample(FileSystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_log
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int deleteByExample(FileSystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_log
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_log
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int insert(FileSystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_log
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int insertSelective(FileSystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_log
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    List<FileSystemLog> selectByExample(FileSystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_log
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    FileSystemLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_log
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") FileSystemLog record, @Param("example") FileSystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_log
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int updateByExample(@Param("record") FileSystemLog record, @Param("example") FileSystemLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_log
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int updateByPrimaryKeySelective(FileSystemLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system_log
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int updateByPrimaryKey(FileSystemLog record);
}