package com.microclouds.dao;

import com.microclouds.pojo.FileSystem;
import com.microclouds.pojo.FileSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    long countByExample(FileSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int deleteByExample(FileSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int insert(FileSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int insertSelective(FileSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    List<FileSystem> selectByExample(FileSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    FileSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") FileSystem record, @Param("example") FileSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int updateByExample(@Param("record") FileSystem record, @Param("example") FileSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int updateByPrimaryKeySelective(FileSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_system
     *
     * @mbg.generated Sat Jan 12 14:49:18 CST 2019
     */
    int updateByPrimaryKey(FileSystem record);
}