package com.microclouds.dao;

import com.microclouds.pojo.UserDetail;
import com.microclouds.pojo.UserDetailExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Sat Dec 29 22:38:17 CST 2018
     */
    long countByExample(UserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Sat Dec 29 22:38:17 CST 2018
     */
    int deleteByExample(UserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Sat Dec 29 22:38:17 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Sat Dec 29 22:38:17 CST 2018
     */
    int insert(UserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Sat Dec 29 22:38:17 CST 2018
     */
    int insertSelective(UserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Sat Dec 29 22:38:17 CST 2018
     */
    List<UserDetail> selectByExample(UserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Sat Dec 29 22:38:17 CST 2018
     */
    UserDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Sat Dec 29 22:38:17 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserDetail record, @Param("example") UserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Sat Dec 29 22:38:17 CST 2018
     */
    int updateByExample(@Param("record") UserDetail record, @Param("example") UserDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Sat Dec 29 22:38:17 CST 2018
     */
    int updateByPrimaryKeySelective(UserDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_detail
     *
     * @mbg.generated Sat Dec 29 22:38:17 CST 2018
     */
    int updateByPrimaryKey(UserDetail record);
}